[package]
name = "file-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.2", features = ["csr"] }
wasm-bindgen = "0.2.99"
